feat: Add COMSEC onboarding
auxolotl/wiki pull request #2
Opened 2024-05-11 18:19 UTC by dantefromhell

First draft

2024-05-11 18:19 UTC, dantefromhell commented
@christoph-heiss Do you mind taking a look please?

2024-05-11 19:55 UTC, christoph-heiss approved these changes
LGTM, thanks for the great work as always!

2024-05-11 20:26 UTC, Minion3665 requested changes

2024-05-11 20:26 UTC, Minion3665 commented on contributing/sigs-and-committees/security/onboarding.md
> +# Committee Security - Onboarding
It would be nice to have some metadata here for wiki.js to see page titles etc.
Here's an example of what that could look like https://github.com/auxolotl/wiki/blob/4cb66529bdb4e01235538dbdce7c3ecd697e2e10/contributing/sigs-and-committees/committees.md?plain=1#L1-L9

2024-05-11 20:26 UTC, Minion3665 commented on contributing/sigs-and-committees/security/welcome.md
> +# Welcome to Committee "Security"
It would be nice to have some metadata here for wiki.js to see page titles etc.
Here's an example of what that could look like https://github.com/auxolotl/wiki/blob/4cb66529bdb4e01235538dbdce7c3ecd697e2e10/contributing/sigs-and-committees/committees.md?plain=1#L1-L9

2024-05-12 16:29 UTC, dantefromhell commented on contributing/sigs-and-committees/security/onboarding.md
> +# Committee Security - Onboarding
Done

2024-05-12 16:30 UTC, dantefromhell commented on contributing/sigs-and-committees/security/welcome.md
> +# Welcome to Committee "Security"
done

2024-05-12 16:34 UTC, Minion3665 approved these changes
thanks very much!

2024-05-12 16:59 UTC, merged